name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --ignore-patterns=venv,test --recursive=true -j 0 --disable=C0103,C0114,C0115,C0302,R0902,R0903,R0913,W1203 --max-line-length=120 --extension-pkg-whitelist="pydantic,asyncpg" --ignored-modules=alembic.context,alembic.op .
